apiVersion: apps/v1
kind: Deployment
metadata:
  name: evil-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evil
  template:
    metadata:
      labels:
        app: evil
    spec:
      containers:
      - name: nginx
        image: nginx
        securityContext:
          privileged: true
