apiVersion: apps/v1
kind: Deployment
metadata:
  name: good-nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: good-nginx
  template:
    metadata:
      labels:
        app: good-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
